apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  spring.data.mongodb.authentication-database: {{ .Values.mongodb.authentication.database }}
  spring.data.mongodb.uri: {{ .Values.mongodb.uri }}