apiVersion: batch/v1
kind: Job
metadata:
  name: k6-performance-test
spec:
  template:
    metadata:
      name: k6-performance-test
    spec:
      containers:
        - name: k6
          image: loadimpact/k6
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "400Mi"
          args: ["run", "-o", "influxdb=http://my-influxdb:8086", "https://raw.githubusercontent.com/benjb59/demo-backend/mongodb/.k6/stress.js"]
      restartPolicy: Never